### ISSUE TITLE
Raxezdev.com url in admin themes description redirect to a adware page

### ISSUE THREAD

**Issue by CraftedRO** [FusionGen/FusionGEN#64] opened 2021-04-04 09:31 UTC
**Describe the bug**

PHP version | 7.1.33
-- | --
CMS version | 1.0.1

Im using srp6 branch ccad9b1

When you first time click on the Jesper Lindström description link in http://localhost/admin/theme you are being redirected to an adware page like in my screenshoot .

**To Reproduce**
1. Go to 'http://localhost/admin/theme'
2. Click on 'Jesper Lindström'

**Expected behavior**
Since that url isn't valid I propose to change it to https://jesperlindstrom.se or https://github.com/jesperlindstrom if this is the guy where credit for other themes goes in Json description of each theme.

**Screenshots**
![fusioncmslinkvirus](https://user-images.githubusercontent.com/24683355/113504487-0e48d880-9541-11eb-839a-66165d826b97.JPG)

**Additional context**

**Comment by OMGhixD-OG** [comment] 2021-04-04 23:55
This is not a bug? This is the Author URL set by the creator.

Its relatively easy to resolve tho, Fixed as of https://github.com/FusionGen/FusionGEN/commit/97cdddd55c3bb633bbdca89244400f82c233da5e and https://github.com/FusionGen/FusionGEN/commit/c5eedee09f8fcbf8963c4427cb8716a795d034e6

**Closed by OMGhixD-OG** 2021-04-04 23:55 UTC
