### ISSUE TITLE
Admin Accounts search function doesn't result anything

### ISSUE THREAD

**Issue by CraftedRO** [FusionGen/FusionGEN#60] opened 2021-04-01 11:44 UTC
**Describe the bug**
Tested on https://github.com/FusionGen/FusionGEN/commit/2534d25399227c24fb26813a64a45a2b23b714e7 srp6 branch

PHP version | 7.1.33
-- | --
CMS version | 1.0.1

Go to http://localhost/admin/accounts then search for username / email .
Notice the errors in console tools.

**To Reproduce**
1. Go to 'http://localhost/admin/accounts'
2. Fill the box with a valid username or email
3. Click on 'Search'

**Expected behavior**
It shoud result the requested account name and if I remember right you shoud be able to modify currency.

**Screenshots**
![Capturegen](https://user-images.githubusercontent.com/24683355/113288947-3d203e00-92f8-11eb-82ca-d5e85a535e33.JPG)

**Additional context**
http://localhost/application/themes/admin/images/ajax.gif is missing too.

**Comment by xabos** [comment] 2021-04-01 11:53
it's only this the problem everything else works fine??

**Comment by CraftedRO** [comment] 2021-04-01 12:00
Not sure what you mean by everything else .

**Comment by xabos** [comment] 2021-04-01 12:02
item store onliine player server armory

**Comment by CraftedRO** [comment] 2021-04-01 12:05
items store dosen't send the item to character : [see issue](https://github.com/FusionGen/FusionGEN/issues/61)
online players it works and default armory works too .

**Comment by OMGhixD-OG** [comment] 2021-04-02 10:28
You must seriously have missed some of the settup requirements. Do you have every Module and Extension required enabled?

**Comment by CraftedRO** [comment] 2021-04-02 10:37
sure
![modules](https://user-images.githubusercontent.com/24683355/113408717-8e900200-93b8-11eb-8e5c-1178fadd74ee.JPG)

**Comment by OMGhixD-OG** [comment] 2021-04-02 10:38
No i meant Apache Modules and PHP Extensions...?

**Comment by Err0r1** [comment] 2021-04-02 10:43
The site /erros gives a 403 - Forbidden error.
This is the first indication that the webserver is configured incorrectly

 Error 500 - Internal server error is the 2nd indication.

But the issue is confirmed

The database structure has changed with SRP6.

**Comment by CraftedRO** [comment] 2021-04-02 10:44
If I remember right I only needed to enable extension=php_soap.dll and extension=php_gmp.dll in php.ini and the requirements passed .

**Comment by OMGhixD-OG** [comment] 2021-04-02 10:46
![unknown](https://user-images.githubusercontent.com/3145839/113409364-68b32f00-93b1-11eb-986d-424534db7a43.png)

Double check your requirements..

**Comment by OMGhixD-OG** [comment] 2021-04-02 10:47
> The site /erros gives a 403 - Forbidden error.
> This is the first indication that the webserver is configured incorrectly
> 
> Error 500 - Internal server error is the 2nd indication.
> 
> But the issue is confirmed
> 
> The database structure has changed with SRP6.

What? Then the issue is poorly documented. We should start a fresh report. Without all the chitchat nonsense and include only relative context.

**Comment by Err0r1** [comment] 2021-04-02 10:49
I agree.
Issue is caused of wrong DB structure (session_key to sessionKey e.g.)

Can be closed, pls open a new report. Issue has nothing to do with webserver or requirements.

**Comment by CraftedRO** [comment] 2021-04-02 10:57
I enable the last remained uncommented extension openssl but still same problem even after restarting the apache.

**Comment by Err0r1** [comment] 2021-04-02 11:49
After some testing, its a bit weird
s, v, sessionkey doesn't exist in srp6 (azerothcore). "save" want to empty the fields, although they don't exist, there is no error.
If they exist, it doesn't empty it

But I can't reproduce the 500 error

**Comment by xabos** [comment] 2021-04-02 12:21
he using trinity core emulator

> After some testing, its a bit weird
> s, v, sessionkey doesn't exist in srp6 (azerothcore). "save" want to empty the fields, although they don't exist, there is no error.
> If they exist, it doesn't empty it
> 
> But I can't reproduce the 500 error

**Comment by Err0r1** [comment] 2021-04-02 12:23
> he using trinity core emulator
> 
> > After some testing, its a bit weird
> > s, v, sessionkey doesn't exist in srp6 (azerothcore). "save" want to empty the fields, although they don't exist, there is no error.
> > If they exist, it doesn't empty it
> > But I can't reproduce the 500 error

Trinity, Azeroth, doesn't matter mate
Both use SRP6

**Comment by xabos** [comment] 2021-04-02 12:24
> > he using trinity core emulator
> > > After some testing, its a bit weird
> > > s, v, sessionkey doesn't exist in srp6 (azerothcore). "save" want to empty the fields, although they don't exist, there is no error.
> > > If they exist, it doesn't empty it
> > > But I can't reproduce the 500 error
> 
> Trinity, Azeroth, doesn't matter mate
> Both use SRP6

I have azerothcore and it's working correctly only with the azerothcore_emulator

**Comment by ErnestoGonzalezC** [comment] 2021-04-10 14:12
> Habilito la última extensión sin comentar openssl pero sigue siendo el mismo problema incluso después de reiniciar el apache.

Remember that the extensions must be installed and then enabled, the order does not matter just remember to do the 2 things and restart apache.

**Comment by Aps05** [comment] 2021-04-20 06:18
I've just confirmed this issue. The problem is that the database structure in TrinityCore was updated. Here is the SQL error:

![image](https://user-images.githubusercontent.com/8566325/115346468-dedcd180-a1b8-11eb-80de-b33e2d5a94cd.png)

The new field names are
`AccountID, SecurityLevel, RealmID`

Please note I'm using master-srp6.

**Comment by favorit5503** [comment] 2021-04-20 12:20
I think this will be an emulator problem. Becouse for me its working. What expansion what core and what amulator are you using?

**Comment by Aps05** [comment] 2021-04-20 12:28
It is an issue related to a specific emulator yes, that's why I specified TrinityCore. Both TrinityCore master and 3.3.5 use the same table structure (the one specified in my previous comment).

I'm using a fresh clone of FusionGEN master-srp6 and TrinityCore 3.3.5.

**Comment by OMGhixD-OG** [comment] 2021-04-20 12:58
it is a rather simple fix. We'll need the Column Structure of account_access.

Sooo if this can be provided by someone. That would be nice!

Thank you.

**Comment by Aps05** [comment] 2021-04-20 13:00
Of course! You can find the table structure below:

CREATE TABLE `account_access` (
  `AccountID` int(10) unsigned NOT NULL,
  `SecurityLevel` tinyint(3) unsigned NOT NULL,
  `RealmID` int(11) NOT NULL DEFAULT '-1',
  `Comment` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`AccountID`,`RealmID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

Thank you for the prompt response.

**Comment by CraftedRO** [comment] 2021-04-20 13:02
well I tryed something and is not simple as we think :)

**Comment by OMGhixD-OG** [comment] 2021-04-20 13:24
Try to pull and see if it improves.

**Comment by CraftedRO** [comment] 2021-04-20 13:26
already tried 
`ERROR - 2021-04-20 15:26:19 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM account_access WHERE id = '1'' at line 1`

**Comment by OMGhixD-OG** [comment] 2021-04-20 13:28
> already tried
> `ERROR - 2021-04-20 15:26:19 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM account_access WHERE id = '1'' at line 1`

Ok, we still need to do this as it is a structural update. Now onto resolving the remaining issues.

**Comment by OMGhixD-OG** [comment] 2021-04-20 13:31
And now?

After commit https://github.com/FusionGen/FusionGEN/commit/4dcf298ee5313055911912af26307c80906f0ddb

**Comment by CraftedRO** [comment] 2021-04-20 13:34
same

**Comment by Err0r1** [comment] 2021-04-20 13:36
Its not just "change emulator structure"
You have to check out other files aswell
Check this commit: https://github.com/Err0r1/FusionGEN/commit/474143304f2943452d3d4d69283c40b35426a0cc

**Comment by OMGhixD-OG** [comment] 2021-04-20 13:37
> Its not just "change emulator structure"
> You have to change other files aswell
> Check this commit: [Err0r1@4741433](https://github.com/Err0r1/FusionGEN/commit/474143304f2943452d3d4d69283c40b35426a0cc)

Well sure, but we also have to change the structure..?

**Comment by Err0r1** [comment] 2021-04-20 13:39
> > Its not just "change emulator structure"
> > You have to change other files aswell
> > Check this commit: [Err0r1@4741433](https://github.com/Err0r1/FusionGEN/commit/474143304f2943452d3d4d69283c40b35426a0cc)
> 
> Well sure, but we also have to change the structure..?

Yes, i did it alrdy on the commit and check if trinity

**Comment by OMGhixD-OG** [comment] 2021-04-20 13:40
> > > Its not just "change emulator structure"
> > > You have to change other files aswell
> > > Check this commit: [Err0r1@4741433](https://github.com/Err0r1/FusionGEN/commit/474143304f2943452d3d4d69283c40b35426a0cc)
> > 
> > 
> > Well sure, but we also have to change the structure..?
> 
> Yes, i did it alrdy on the commit and check if trinity
> idk if azerothcore or other cores will change it or not.. we have to change it then

Surely, would you be ok with me cherrypicking things from the commit you linked?

**Comment by Err0r1** [comment] 2021-04-20 13:41
> > > > Its not just "change emulator structure"
> > > > You have to change other files aswell
> > > > Check this commit: [Err0r1@4741433](https://github.com/Err0r1/FusionGEN/commit/474143304f2943452d3d4d69283c40b35426a0cc)
> > > 
> > > 
> > > Well sure, but we also have to change the structure..?
> > 
> > 
> > Yes, i did it alrdy on the commit and check if trinity
> > idk if azerothcore or other cores will change it or not.. we have to change it then
> 
> Surely, would you be ok with me cherrypicking things from the commit you linked?

yeah sure.

**Comment by CraftedRO** [comment] 2021-04-20 13:43
most likely if we fix this for TC then it will broke for AC :)

**Comment by Err0r1** [comment] 2021-04-20 13:46
> most likely if we fix this for TC then it will broke for AC :)

No..
i checked if trinity (SecurityLevel) or azerothcore (gmlevel) 
We just need more checks if SecurityLevel or gmlevel

**Comment by OMGhixD-OG** [comment] 2021-04-20 13:46
> most likely if we fix this for TC then it will broke for AC :)

I dont think so. I can see that Err0r1 has taken use of "if trinitycore emulator" statements in his commit. Which would only really apply it if it is a trinitycore emulator being selected. 

And AC usually updates with TC, i mean they did with SRP6 so whynot with this?

**Comment by Err0r1** [comment] 2021-04-20 20:12
Should be fixes with https://github.com/FusionGen/FusionGEN/pull/73 for AC & TC

**Comment by OMGhixD-OG** [comment] 2021-04-20 20:14
Merged. Awaiting some test results.

**Comment by Aps05** [comment] 2021-04-20 20:53
Same issue for me I'm afraid. When I try to search for a user, the SQL it tries to run is this:
`SELECT FROM account_access WHERE = '3'`

**Comment by CraftedRO** [comment] 2021-04-20 20:55
indeed same here : 
`ERROR - 2021-04-20 22:54:02 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM account_access WHERE  = '1'' at line 1`

**Comment by OMGhixD-OG** [comment] 2021-04-20 20:55
Please. No need for multiple confirmations. One is enough.. dont want this to become flooded with repetivity.

**Comment by Err0r1** [comment] 2021-04-20 20:59
> Same issue for me I'm afraid. When I try to search for a user, the SQL it tries to run is this:
> `SELECT FROM account_access WHERE = '3'`

Update, delete cache, try again pls

**Comment by Aps05** [comment] 2021-04-21 05:53
I pulled, cleared all cache from the 'Manage Cache' page in the admin and tried again. Same error.

**Comment by Err0r1** [comment] 2021-04-21 06:56
Ok, will check it when i'm at home

**Comment by Err0r1** [comment] 2021-04-24 13:24
Issue fixed.

- Close request

**Closed** 2021-04-24 14:30 UTC
